# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'


target 'client-server-1347' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  
  # Pods for client-server-1347

  pod 'Alamofire'
  pod 'SwiftKeychainWrapper'
  pod 'RealmSwift'
  pod 'SwiftyJSON'
  pod 'SDWebImage'
  pod 'ReachabilitySwift'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  pod 'FirebaseUI/Storage'
  pod 'KeychainAccess'
  pod 'AlamofireImage'
  pod 'Kingfisher'
  pod 'ImageViewer.swift', '~> 3.0'
  pod 'PromiseKit'
  pod 'ExpandableLabel'
end
